# Generated by Django 3.1.3 on 2020-11-19 15:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nieruchomosci',
            old_name='cena',
            new_name='cena_do',
        ),
        migrations.RemoveField(
            model_name='zrodla',
            name='nazwa',
        ),
        migrations.AddField(
            model_name='nieruchomosci',
            name='cena_od',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nieruchomosci',
            name='rodzaj',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('D', 'Dowolny'), ('A', 'Apartamentowiec'), ('B', 'Blok'), ('D', 'Dom'), ('K', 'Kamienica')], max_length=100),
        ),
    ]
