# Generated by Django 3.1.3 on 2020-11-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0002_auto_20201119_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='zrodla',
            name='nazwa1',
            field=models.CharField(default='morizon.pl', max_length=100),
        ),
        migrations.AddField(
            model_name='zrodla',
            name='nazwa2',
            field=models.CharField(default='gratka.pl', max_length=100),
        ),
    ]
