# Generated by Django 3.1.3 on 2020-11-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0003_auto_20201119_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zrodla',
            name='nazwa1',
        ),
        migrations.RemoveField(
            model_name='zrodla',
            name='nazwa2',
        ),
        migrations.AddField(
            model_name='zrodla',
            name='nazwa',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
