# Generated by Django 3.1.3 on 2020-11-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0005_auto_20201119_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zrodla',
            old_name='nazwa1',
            new_name='nazwa',
        ),
        migrations.RemoveField(
            model_name='zrodla',
            name='nazwa2',
        ),
    ]
