# Generated by Django 3.1.3 on 2020-11-19 18:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0006_auto_20201119_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nieruchomosci',
            name='zrodlo',
        ),
        migrations.AddField(
            model_name='nieruchomosci',
            name='zrodla',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'morizon.pl'), ('g', 'gratka.pl'), ('gum', 'gumtree.pl'), ('o', 'otodom.pl'), ('d', 'domiporta.pl'), ('o', 'olx.pl'), ('sz', 'szybko.pl')], default='m', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nieruchomosci',
            name='cena_do',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='nieruchomosci',
            name='cena_od',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='nieruchomosci',
            name='data_dodania',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='nieruchomosci',
            name='opis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nieruchomosci',
            name='rodzaj',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('D', 'Dowolny'), ('A', 'Apartamentowiec'), ('B', 'Blok'), ('D', 'Dom'), ('K', 'Kamienica')], default='D', max_length=100),
        ),
        migrations.AlterField(
            model_name='nieruchomosci',
            name='transakcja',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'Sprzedarz'), ('W', 'Wynajem')], max_length=100),
        ),
    ]
