# Generated by Django 3.1.3 on 2020-11-26 15:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0008_auto_20201120_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='nieruchomosci',
            name='rodzaj_zabudowy',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('d', 'Dowolny'), ('A', 'Apartamentowiec'), ('B', 'Blok'), ('D', 'Dom'), ('K', 'Kamienica')], default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nieruchomosci',
            name='rodzaj',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('D', 'Dowolny'), ('Domy', 'Domy'), ('K', 'Komercyjne'), ('Dz', 'Działki')], default='D', max_length=100),
        ),
    ]
