# Generated by Django 3.1.3 on 2020-11-26 17:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0011_auto_20201126_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nieruchomosci',
            name='rodzaj',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('D', 'Dowolny'), ('M', 'Mieszkania'), ('Domy', 'Domy'), ('K', 'Komercyjne'), ('Dz', 'Działki')], default='D', max_length=100),
        ),
    ]
