# Generated by Django 3.1.3 on 2020-11-26 22:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0012_auto_20201126_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nieruchomosci',
            name='transakcja',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Sprzedarz'), ('W', 'Wynajem')], default='S', max_length=100),
        ),
    ]
