# Generated by Django 3.1.3 on 2020-11-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0014_auto_20201130_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nieruchomosci',
            name='rodzaj_zabudowy',
            field=models.CharField(choices=[('d', 'Dowolny'), ('A', 'Apartamentowiec'), ('B', 'Blok'), ('D', 'Dom'), ('K', 'Kamienica')], default='d', max_length=100),
        ),
    ]
