# Generated by Django 3.1.3 on 2020-12-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0015_auto_20201130_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nieruchomosci',
            name='lokalizacja',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
