# Generated by Django 3.1.3 on 2020-12-07 15:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0016_auto_20201201_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nieruchomosci',
            name='rodzaj',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('D', 'Dowolny'), ('M', models.CharField(choices=[('d', 'Dowolny'), ('A', 'Apartamentowiec'), ('B', 'Blok'), ('D', 'Dom'), ('K', 'Kamienica')], default='d', max_length=100)), ('Domy', 'Domy'), ('K', 'Komercyjne'), ('Dz', 'Działki')], default='D', max_length=100),
        ),
    ]
