# Generated by Django 3.1.3 on 2021-01-07 17:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0018_auto_20201207_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='nieruchomosci',
            name='komercyjne',
            field=models.CharField(choices=[('D', 'Dowolny'), ('B', 'Biura'), ('H', 'Hale i Magazyny')], default='D', max_length=100),
        ),
        migrations.AddField(
            model_name='nieruchomosci',
            name='typ_domu',
            field=models.CharField(choices=[('D', 'Dowolny'), ('W', 'Wolnostojacy'), ('B', 'Blizniak'), ('P', 'Pałac/Dworek'), ('A', 'Atrialny'), ('L', 'Letniskowy'), ('Sz', 'Szeregowiec'), ('K', 'Kamienica'), ('B', 'Blok'), ('G', 'Gospodarstwo')], default='D', max_length=100),
        ),
        migrations.AddField(
            model_name='nieruchomosci',
            name='typ_dzialki',
            field=models.CharField(choices=[('D', 'Dowolny'), ('R', 'Rolna'), ('B', 'Budowlana'), ('L', 'Leśna'), ('Re', 'Rekreacyjna'), ('S', 'Siedliskowa'), ('P', 'Przemysłowa'), ('I', 'Inwestycyjna')], default='D', max_length=100),
        ),
        migrations.AlterField(
            model_name='nieruchomosci',
            name='rodzaj',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('D', 'Dowolny'), ('M', 'Mieszkania'), ('Domy', 'Domy'), ('K', 'Komercyjne'), ('Dz', 'Działki'), ('G', 'Garaże'), ('P', 'Pokoje')], default='D', max_length=100),
        ),
    ]
