# Generated by Django 3.1.3 on 2021-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0019_auto_20210107_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nieruchomosci',
            name='rodzaj',
            field=models.CharField(choices=[('D', 'Dowolny'), ('M', 'Mieszkania'), ('Domy', 'Domy'), ('K', 'Komercyjne'), ('Dz', 'Działki'), ('G', 'Garaże'), ('P', 'Pokoje')], default='D', max_length=100),
        ),
        migrations.AlterField(
            model_name='nieruchomosci',
            name='transakcja',
            field=models.CharField(choices=[('S', 'Sprzedarz'), ('W', 'Wynajem')], default='S', max_length=100),
        ),
    ]
