# Generated by Django 3.1.3 on 2021-02-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nieruchomość', '0020_auto_20210107_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nieruchomosci',
            name='cena_do',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='nieruchomosci',
            name='cena_od',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
    ]
